name: Convert

on:
  push:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formats: [docx, pdf, epub, html]
        fileNames: [README]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Convert "${{ matrix.fileNames }}.md" to ${{ matrix.formats }}
        uses: docker://pandoc/typst:3.8
        with:
          args: --pdf-engine=typst --pdf-engine-opt=--pdf-standard=a-2b --output=${{ matrix.fileNames }}.${{ matrix.formats }} --from=markdown --to=${{ matrix.formats }} ${{ matrix.fileNames }}.md

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.fileNames }}.${{ matrix.formats }}
          path: ${{ matrix.fileNames }}.${{ matrix.formats }}
