name: Convert

on:
  push:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        formats: [html, epub, docx, pdf]
        fileNames: [README]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Convert "${{ matrix.fileNames }}.md" to ${{ matrix.formats }}
        uses: docker://pandoc/latex:3.9
        with:
          args: >-
            --standalone
            --output=${{ matrix.fileNames }}.${{ matrix.formats }}
            ${{ matrix.fileNames }}.md

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.fileNames }}.${{ matrix.formats }}
          path: ${{ matrix.fileNames }}.${{ matrix.formats }}
