name: Generate Documents

on:
  push:
    branches: [main, draft]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Removed PDF generation as Pandoc via Latex was running into issues converting the document.
        formats: [html, epub, docx]
        fileNames: [trust-meter-tech-spec, spécification-technique-indicateur-de-confiance]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Convert "${{ matrix.fileNames }}.md" to ${{ matrix.formats }}
        uses: docker://pandoc/latex:3.9
        with:
          args: >-
            --standalone
            --number-sections
            -f markdown
            -t ${{ matrix.formats }}
            -o "${{ matrix.fileNames }}.${{ matrix.formats }}"
            "./${{ matrix.fileNames }}.md"

      - name: Upload "${{ matrix.fileNames }}.${{ matrix.formats }}"
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.fileNames }}.${{ matrix.formats }}"
          path: "${{ matrix.fileNames }}.${{ matrix.formats }}"
